controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

admins:
    resource: ../../src/Controller/Admin
    type: annotation
    prefix: '/admin'
